name: colibri
description: Colibri

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-numer, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 2.0.1+13

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # for functional programming
  dartz: ^0.10.1
  # for api calls
  dio: ^3.0.10
  # Goolge fonts
  google_fonts: ^1.1.2
  flutter_hooks: ^0.18.5+1
#  auto_route: 0.6.9
#  auto_route: 2.0.0
  flutter_screenutil: ^5.6.0
  rxdart: ^0.25.0
#  flutter_svg: ^0.18.0
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.1
#  flutter_bloc: ^6.0.5
  freezed: ^0.14.1+2
  freezed_annotation:
  equatable: ^2.0.5
  injectable: ^1.0.5
  get_it: ^7.2.0
  flushbar: ^1.10.4
  flutter_webview_plugin: ^0.4.0
  font_awesome_flutter: ^10.2.1
  cached_network_image: ^2.3.2+1
  image_picker: ^0.6.7+22
  emoji_picker:
    git:
      url: https://github.com/JeffG05/emoji_picker.git
      ref: e51ffca492de3e43a09e7450638e29f4ee63fec5
  flutter_animated_dialog: ^2.0.1
  giphy_picker: ^1.0.6
  flutter_secure_storage: ^4.2.1
  intl: ^0.16.1
  carousel_slider: ^4.1.1
  video_thumbnail: ^0.5.3
  video_player:
#  video_player: 0.11.0
  photo_view: ^0.14.0
  flutter_vlc_player: ^5.0.5
  file_picker: ^2.1.7
  photo: ^0.4.8
#  wechat_assets_picker:
#  wechat_assets_picker: ^4.2.2
  thumbnails: ^1.0.1
  path_provider: ^1.6.28
  video_compress: ^3.1.2
  flutter_easyloading: ^3.0.5
  permission_handler: ^5.0.0+hotfix.4
  better_player: 0.0.61
#  awesome_dialog: ^1.2.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.6
#  flutter_twitter_login: ^1.1.0
#  i18n_extension: ^1.4.2
#  easy_localization: ^2.2.3
  infinite_scroll_pagination: ^3.2.0
#  pretty_dio_logger: ^1.1.1
#  copy_with_extension_gen: ^1.4.0
  faker: ^2.0.0
#  flutter_swiper: ^1.1.6
  native_device_orientation: ^1.1.4
  mime: ^1.0.2
  velocity_x: ^1.3.1
  timelines: ^0.1.0
  url_launcher: ^5.7.10
  animations: ^2.0.7
  smart_select: ^4.3.2
  html_unescape: ^2.0.0
  flutter_linkify: ^5.0.2
#  social_share: ^2.0.5
  share: any
  webview_flutter: ^2.0.14
  shared_preferences: ^0.5.12+4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  material_floating_search_bar: ^0.3.7
  pull_to_refresh: ^2.0.0
  flutter_apns: ^1.4.1
  flutter_local_notifications: ^4.0.1+2
  image_cropper: ^1.3.1
  expandable_page_view: ^1.0.1
  flutter_image_compress: ^1.1.3
  file_utils: ^1.0.1
  firebase_messaging: ^7.0.3
  keyboard_actions: ^4.1.0
  clipboard_manager: ^0.0.4

  firebase_auth: ^0.18.3
#  firebase_core: ^0.7.0

#  flutter_timeline: ^0.1.1+13
  remove_emoji: ^0.0.1
#  flutter_html: ^0.11.1
  page_indicator:
  page_view_indicators: ^2.0.0
  modal_bottom_sheet: ^2.0.0
#  auto_size_text: ^2.1.0
#  add_thumbnail: 0.0.1
  html: ^0.14.0
  keyboard_visibility: ^0.5.6
  simple_url_preview: ^2.0.0
#  flick_video_player: 0.3.0
  youtube_player_flutter: ^8.0.0
#  any_link_preview: ^1.0.8
  flutter_link_preview: ^1.5.6
  awsome_video_player:
#  videos_player:


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^1.0.2
  build_runner:
  injectable_generator: ^1.0.5
  copy_with_extension_gen: ^2.0.2
  flutter_keyboard_visibility: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/png_image/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
#    - family: Avenir
#      fonts:
#        - asset: fonts/AvenirNextLTPro-Light.ttf
#          weight: 200
#        - asset: fonts/AvenirNextLTPro-Regular.ttf
#          weight: 400
#        - asset: fonts/AvenirNextLTPro-Heavy.ttf
#          weight: 600
    - family: Campton
      fonts:
        - asset: fonts/Campton-Light.ttf
          weight: 200
        - asset: fonts/Campton-Medium.ttf
          weight: 400
        - asset: fonts/Campton-Bold.ttf
          weight: 600
    - family: CeraPro
      fonts:
        - asset: fonts/CeraPro-Regular.ttf
          weight: 200
        - asset: fonts/CeraPro-Medium.ttf
          weight: 400
        - asset: fonts/CeraPro-Bold.ttf
          weight: 600

#        - asset: fonts/AvenirNextLTPro-Bold.ttf
#          weight: 600



  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
